version: '3.8'

services:
  app:
     build: .
     container_name: app-masterpol-container
     restart: unless-stopped
     environment:
       - DB_HOST=db
       - DB_USER=${DB_USER}
       - DB_PASS=${DB_PASS}
       - DB_PORT=5432
       - DB_NAME=${DB_NAME}
       - LOG_FILE=/app/logs/app.log
     ports:
       - "8000:8000"
     depends_on:
       db:
         condition: service_healthy
     volumes:
       - .:/app:ro
       - ./logs:/app/logs
     networks:
       - app_network

  db:
    image: postgres:17.5
    container_name: db-masterpol-container
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-masterpol-container
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network

volumes:
  postgres_data:
  app_logs:
  pgadmin_data:

networks:
  app_network:
    driver: bridge