"""Update constraints

Revision ID: f035437d96ba
Revises: 698c342fe673
Create Date: 2025-06-15 23:05:26.617104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f035437d96ba"
down_revision: Union[str, None] = "698c342fe673"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "materials", ["id"])
    op.create_unique_constraint(None, "partners", ["id"])
    op.create_unique_constraint(None, "products_import", ["id"])
    op.create_unique_constraint(None, "products_types", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "products_types", type_="unique")
    op.drop_constraint(None, "products_import", type_="unique")
    op.drop_constraint(None, "partners", type_="unique")
    op.drop_constraint(None, "materials", type_="unique")
    # ### end Alembic commands ###
