"""Create rel for products & products_import

Revision ID: 5e5af871abbe
Revises: dc5a0ff4511f
Create Date: 2025-06-11 21:29:25.644125

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e5af871abbe"
down_revision: Union[str, None] = "dc5a0ff4511f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("product_import_id", sa.UUID(), nullable=False))
    op.create_unique_constraint(None, "products", ["id"])
    op.create_foreign_key(None, "products", "products_import", ["product_import_id"], ["id"])
    op.drop_column("products", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("products", "product_import_id")
    # ### end Alembic commands ###
