"""Add statuses for Partners

Revision ID: 698c342fe673
Revises: 5e5af871abbe
Create Date: 2025-06-15 22:47:08.265281

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

from src.infrastructure.database.enums.partner_statuses import PartnerStatuses


# revision identifiers, used by Alembic.
revision: str = "698c342fe673"
down_revision: Union[str, None] = "5e5af871abbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    partner_statuses = postgresql.ENUM("active", "pending", name="partnerstatuses")
    partner_statuses.create(op.get_bind())

    op.add_column(
        "partners",
        sa.Column(
            "status",
            sa.Enum("active", "pending", name="partnerstatuses"),
            nullable=True,
        ),
    )

    op.execute("UPDATE partners SET status = 'active' WHERE status IS NULL")

    op.alter_column(
        "partners",
        "status",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("partners", "status")

    partner_statuses = postgresql.ENUM("active", "pending", name="partnerstatuses")
    partner_statuses.drop(op.get_bind())
    # ### end Alembic commands ###
